---
# Per environment values which override defaults in yjb-platform/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: yjb-platform-dev.apps.live.cloud-platform.service.justice.gov.uk

  env:
    INGRESS_URL: "https://yjb-platform-dev.apps.live.cloud-platform.service.justice.gov.uk"
#    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
#    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    API_URL: 'https://yjb-platform-api-dev.apps.live.cloud-platform.service.justice.gov.uk/'
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: NON_PROD_ALERTS_SEVERITY_LABEL
