name: Build & push docker image and deploy to environment

on:
  workflow_call:
    inputs:
      docker_registry:
        description: Docker registry
        required: true
        type: string
      registry_org:
        description: Docker registry organisation
        required: true
        type: string
      additional_docker_tag:
        description: Additional docker tag that can be used to specify stable tags
        required: false
        type: string
      tag_latest:
        description: Tag docker image as 'latest'
        required: false
        type: boolean
        default: true
      upload_image_artifact:
        description: Upload image to artifacts in GitHub Actions
        required: false
        type: boolean
        default: false
      image_artifact_retention_days:
        description: Number of days to keep the image in artifacts
        required: false
        type: number
        default: 7
      additional_docker_build_args:
        description: Additional docker build arguments
        required: false
        type: string
      push:
        description: Push docker image to registry flag
        required: true
        type: boolean
      load:
        description: Load docker image into local docker
        required: false
        type: boolean
        default: false
      docker_multiplatform:
        description: Docker image build multiplatform or not
        required: true
        type: boolean
        default: true
      image_name:
        description: Name of the image
        required: false
        type: string
      file:
        description: "Path to the Dockerfile"
        required: false
        type: string
      download_build_artifacts:
        description: Whether to download the build artifacts prior to running the docker build
        required: false
        type: boolean
        default: false
      generate_sbom:
        description: Generate an SBOM for the final pushed image and upload it as a workflow artifact
        required: false
        type: boolean
        default: false
      attach_sbom_to_registry:
        description: Create and push an SBOM attestation for the pushed image in the container registry
        required: false
        type: boolean
        default: false
      sign_image:
        description: Sign pushed image digest in the container registry
        required: false
        type: boolean
        default: false
    secrets:
      HMPPS_QUAYIO_USER:
        required: false
      HMPPS_QUAYIO_TOKEN:
        required: false

    outputs:
      app_version:
        description: The version of the app as generated by create_app_version
        value: ${{ jobs.create_version.outputs.version }}

jobs:
  create_version:
    name: Create app version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.app_version.outputs.version }}
    steps:
      - id: app_version
        name: Create application version
        uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/build-test-and-deploy/create_app_version@e0e6abc2f67f2bbb81a74610d6c307ab468a1a77 # v1

  docker_build:
    name: Build linux/amd64 (single)
    if: ${{ ! inputs.docker_multiplatform }}
    needs: [create_version]
    runs-on: ubuntu-latest
    outputs:
      image_digest: ${{ steps.build_docker_step.outputs.digest }}
    steps:
      - id: build_docker_step
        uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/build-test-and-deploy/build_docker@e0e6abc2f67f2bbb81a74610d6c307ab468a1a77 # v1
        if: ${{ inputs.docker_registry == 'ghcr.io' }}
        with:
          image_name: ${{ inputs.image_name || github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          tag_latest: ${{ inputs.tag_latest }}
          upload_image_artifact: ${{ inputs.upload_image_artifact }}
          image_artifact_retention_days: ${{ inputs.image_artifact_retention_days }}
          push: ${{ inputs.push }}
          load: ${{ inputs.load }}
          app_version: ${{ needs.create_version.outputs.version }}
          additional_docker_build_args: ${{ inputs.additional_docker_build_args }}
          file: ${{ inputs.file }}
          download_build_artifacts: ${{ inputs.download_build_artifacts }}

      - uses: ministryofjustice/hmpps-github-shared-actions/.github/actions/build-test-and-deploy/build_docker@e0e6abc2f67f2bbb81a74610d6c307ab468a1a77 # v1
        if: ${{ inputs.docker_registry == 'quay.io' }}
        with:
          image_name: ${{ inputs.image_name || github.event.repository.name }}
          docker_registry: ${{ inputs.docker_registry }}
          registry_org: ${{ inputs.registry_org }}
          additional_docker_tag: ${{ inputs.additional_docker_tag }}
          tag_latest: ${{ inputs.tag_latest }}
          upload_image_artifact: ${{ inputs.upload_image_artifact }}
          image_artifact_retention_days: ${{ inputs.image_artifact_retention_days }}
          push: ${{ inputs.push }}
          load: ${{ inputs.load }}
          app_version: ${{ needs.create_version.outputs.version }}
          HMPPS_QUAYIO_USER: ${{ secrets.HMPPS_QUAYIO_USER }}
          HMPPS_QUAYIO_TOKEN: ${{ secrets.HMPPS_QUAYIO_TOKEN}}
          additional_docker_build_args: ${{ inputs.additional_docker_build_args }}
          download_build_artifacts: ${{ inputs.download_build_artifacts }}

  docker_build_platform:
    name: Build ${{ matrix.platform }} (parallel)
    if: ${{ inputs.docker_multiplatform }}
    needs: [create_version]
    strategy:
      fail-fast: true
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Download build artifacts needed for docker build
        if: ${{ inputs.download_build_artifacts }}
#        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        uses: actions/download-artifact@v4
        with:
          name: build-results

      - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4

      - name: Prepare platform pair
        id: prepare
        shell: bash
        run: |
          echo "platform_pair=${platform//\//-}" >> "$GITHUB_OUTPUT"
        env:
          platform: ${{ matrix.platform }}

      - name: Build docker archive tarball
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          context: .
          platforms: ${{ matrix.platform }}
          file: ${{ inputs.file }}
          build-args: |
            "BUILD_NUMBER=${{ needs.create_version.outputs.version }}"
            "GIT_REF=${{ github.sha }}"
            "GIT_BRANCH=${{ github.ref_name }}"
            "${{ inputs.additional_docker_build_args }}"
          outputs: type=docker,name=${{ inputs.docker_registry }}/${{ inputs.registry_org }}/${{ inputs.image_name || github.event.repository.name }}:${{ needs.create_version.outputs.version }},dest=${{ runner.temp }}/image.tar
          cache-from: type=gha,scope=build-${{ steps.prepare.outputs.platform_pair }}
          cache-to: type=gha,scope=build-${{ steps.prepare.outputs.platform_pair }},mode=max
          provenance: false

      - name: Upload image tarball
        if: ${{ inputs.push || inputs.upload_image_artifact }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: image-${{ steps.prepare.outputs.platform_pair }}
          path: ${{ runner.temp }}/image.tar
          if-no-files-found: error
          retention-days: ${{ inputs.upload_image_artifact && inputs.image_artifact_retention_days || 1 }}

  docker_build_merge:
    name: Push multi-platform image
    if: ${{ inputs.docker_multiplatform && inputs.push }}
    needs: [create_version, docker_build_platform]
#    uses: ./.github/workflows/docker_push.yml
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_push.yml@41ae033
    secrets:
      HMPPS_QUAYIO_USER: ${{ secrets.HMPPS_QUAYIO_USER }}
      HMPPS_QUAYIO_TOKEN: ${{ secrets.HMPPS_QUAYIO_TOKEN }}
    with:
      docker_registry: ${{ inputs.docker_registry }}
      registry_org: ${{ inputs.registry_org }}
      image_name: ${{ inputs.image_name }}
      app_version: ${{ needs.create_version.outputs.version }}
      tag_latest: ${{ inputs.tag_latest }}
      additional_docker_tag: ${{ inputs.additional_docker_tag }}
      docker_multiplatform: true

  sign_image_single_platform:
    name: Sign image (single-platform)
    if: ${{ inputs.sign_image && !inputs.docker_multiplatform && inputs.push && inputs.docker_registry == 'ghcr.io' }}
    needs: [create_version, docker_build]
#    uses: ./.github/workflows/docker_sign.yml
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_sign.yml@41ae033
    with:
      docker_registry: ${{ inputs.docker_registry }}
      registry_org: ${{ inputs.registry_org }}
      image_name: ${{ inputs.image_name }}
      image_digest: ${{ needs.docker_build.outputs.image_digest }}

  sign_image_multi_platform:
    name: Sign image (multi-platform)
    if: ${{ inputs.sign_image && inputs.docker_multiplatform && inputs.push && inputs.docker_registry == 'ghcr.io' }}
    needs: [create_version, docker_build_merge]
#    uses: ./.github/workflows/docker_sign.yml
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_sign.yml@41ae033
    with:
      docker_registry: ${{ inputs.docker_registry }}
      registry_org: ${{ inputs.registry_org }}
      image_name: ${{ inputs.image_name }}
      image_digest: ${{ needs.docker_build_merge.outputs.image_digest }}

  generate_sbom_single_platform:
    name: Generate SBOM (single-platform image)
    if: ${{ inputs.generate_sbom && !inputs.docker_multiplatform && inputs.push && inputs.docker_registry == 'ghcr.io' }}
    needs: [create_version, docker_build]
#    uses: ./.github/workflows/docker_sbom.yml
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_sbom.yml@41ae033
    with:
      docker_registry: ${{ inputs.docker_registry }}
      registry_org: ${{ inputs.registry_org }}
      image_name: ${{ inputs.image_name }}
      app_version: ${{ needs.create_version.outputs.version }}
      image_digest: ${{ needs.docker_build.outputs.image_digest }}
      attach_sbom_to_registry: ${{ inputs.attach_sbom_to_registry }}

  generate_sbom_multi_platform:
    name: Generate SBOM (multi-platform image)
    if: ${{ inputs.generate_sbom && inputs.docker_multiplatform && inputs.push && inputs.docker_registry == 'ghcr.io' }}
    needs: [create_version, docker_build_merge]
    #    uses: ./.github/workflows/docker_sbom.yml
    uses: ministryofjustice/hmpps-github-actions/.github/workflows/docker_sbom.yml@41ae033
    with:
      docker_registry: ${{ inputs.docker_registry }}
      registry_org: ${{ inputs.registry_org }}
      image_name: ${{ inputs.image_name }}
      app_version: ${{ needs.create_version.outputs.version }}
      image_digest: ${{ needs.docker_build_merge.outputs.image_digest }}
      attach_sbom_to_registry: ${{ inputs.attach_sbom_to_registry }}
